use JAVA_APP_JAR & ARTIFACT_COPY_ARGS after all
just like in https://launch.prod-preview.openshift.io/launch/home

because S2I_SOURCE_DEPLOYMENTS_FILTER causes
Exception in thread "main" java.lang.NoClassDefFoundError: io/quarkus/runtime/Application
(the lib copy clearly doesn't quite work)